[project]
name = "embedder"
version = "0.1.0"
description = "Embedding service"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "loguru>=0.7.3",
    "sentence-transformers>=5.2.0",
]
